### ISSUE TITLE
Code style tooling?

### ISSUE THREAD

**Issue by arthurvr** [jquery-boilerplate/jquery-boilerplate#100]
Instead of having to care about code styling ourselves, we should have tooling to do so. [jscs, for example](https://github.com/jscs-dev/grunt-jscs). IMHO we need a jscs grunt task and the necessary configurations for the jQuery style guide.

**Comment by zachofalltrades** [comment]
the boiler plate DOES have a configuration file the JSHint tool -- the file is '.jshintrc'
that said...
 I do have some concerns that the JSHint config file is not consistent with what is recommended on the jQuery style guide. A couple of JSHint options were removed in a recent commit because they are no longer supported by JSHint (which means the jQuery recommendation itself ought to be updated) -- but one of the recommended settings  ("undef": true) appears to have never been included in the boilerplate -- although I have to say that when I do include that option, JSHint starts complaining about missing global objects (such as 'window' and 'document').

**Comment by heldr** [comment]
After #114 and #106 it will use jQuery preset through jscs.

**Comment by heldr** [comment]
jscs is on the latest version with jQuery preset attached
