### ISSUE TITLE
how to call yourOtherFunction method from the "outside" ?

### ISSUE THREAD

**Issue by chrisvaupel** [jquery-boilerplate/jquery-boilerplate#79]
since $('#container').defaultPluginName('yourOtherFunction'); doesn't work im wondering how to call methods inside of a plugin?

**Comment by heldr** [comment]
There are many ways, you can also return the plugin instance instead of chaining.
```js
//jquery.boilerplate.js

$.fn[ pluginName ] = function ( options ) {
  this.each(function() {
    if ( !$.data( this, "plugin_" + pluginName ) ) {
        $.data( this, "plugin_" + pluginName, new Plugin( this, options ) );
    }
  });

  return $.data( this, "plugin_" + pluginName );
};
```
And then
```js
var foobar = $('.foobar').defaultPluginName();

foobar.yourOtherFunction();
```

**Comment by Whip** [comment]
> Why is it this verbose? if you use this as the plugin wrapper:
> 
> ```
> $.fn[pluginName] = function (options) {
>   var plugin;
>   this.each(function() {
>     plugin = $.data(this, 'plugin_' + pluginName);
>     if (!plugin) {
>       plugin = new Plugin(this, options);
>       $.data(this, 'plugin_' + pluginName, plugin);
>     }
>   });
>   return plugin;
> };
> ```
> Then you can call your plugin by:
> 
> ```
> $('#container').defaultPluginName().yourOtherFunction();
> ```

Sorry for commenting on a long closed issue but this exactly what I'm looking for. It worked for the last instance of the element only. How can I get it work on all of them?
@heldr Your code didn't work. I got `foobar = undefined.`

**Comment by flxmrk** [comment]
> > Why is it this verbose? if you use this as the plugin wrapper:
> > ```
> > $.fn[pluginName] = function (options) {
> >   var plugin;
> >   this.each(function() {
> >     plugin = $.data(this, 'plugin_' + pluginName);
> >     if (!plugin) {
> >       plugin = new Plugin(this, options);
> >       $.data(this, 'plugin_' + pluginName, plugin);
> >     }
> >   });
> >   return plugin;
> > };
> > ```
> > Then you can call your plugin by:
> > ```
> > $('#container').defaultPluginName().yourOtherFunction();
> > ```
> 
> Sorry for commenting on a long closed issue but this exactly what I'm looking for. It worked for the last instance of the element only. How can I get it work on all of them?
> @heldr Your code didn't work. I got `foobar = undefined.`

Veek - use my fork - some shortcomings have been fixed:
https://github.com/fmp777/jquery-plugin-boilerplate

**Comment by Whip** [comment]
Correct me if I'm wrong but your approach would give me
```
$('element').myPluginName('myMethod')
```
while I want
```
var instance = $('element').myPluginName;
instance.myMethod();
```

**Comment by flxmrk** [comment]
> Correct me if I'm wrong but your approach would give me
> 
> ```
> $('element').myPluginName('myMethod')
> ```
> 
> while I want
> 
> ```
> var instance = $('element').myPluginName;
> instance.myMethod();
> ```

No, you are right.  I would say what you want would be poor engineering. You'd figure that out much later down the road and wish you didn't engineer that way. Extending your element with all the methods of your plugin can get very messy very fast and produce undesirable and unexpected results as the application grows.  Keeping the methods safely sandboxed inside the plugin which is attached to the element is the best standard.

You can feel free to post any questions on my fork instead of here if you want to understand it better.

**Comment by flxmrk** [comment]
BTW:
Generally you always return the elements matched in plugins so as to not break chaining methodology of jQuery, so its all in "proper practices" 

That being said, you could certainly do it, however, the issue is that you assume $('element') will only match ONE element.  You can't return 5 plugins if it matches 5 elements and use it like you want.  

You can certainly break with recommended practices and make the assumption of only ONE element and certainly you can return the plugin and have what you want - I just would highly advise against it.  You'd be programming yourself into a corner that eventually you'd have to break out of, then you'd have two standards and a confusing app if anyone else every had to come work on it aside from you.

My fork gives you what you need with the most flexibility and it follows standards.  Its not too far off from the way you wanted it.

**Comment by Whip** [comment]
I see. Thanks for your information. I'll try it your way.

**Comment by expressiveco** [comment]
It could be further improved to support multiple elements 

```js
$.fn[pluginName] = function (options) {
  var plugins = this.map(function() {
    var plugin = $.data(this, 'plugin_' + pluginName);
    if (!plugin) {
      plugin = new Plugin(this, options);
      $.data(this, 'plugin_' + pluginName, plugin);
    }
    return plugin;
  });
  return plugins.length == 1 ? plugins[0] : plugins;
};

```

**Comment by expressiveco** [comment]
It could be further improved to support returning multiple plugin instances when there are multiple elements
```js
$.fn[pluginName] = function (options) {
  var plugins = this.map(function() {
    var plugin = $.data(this, 'plugin_' + pluginName);
    if (!plugin) {
      plugin = new Plugin(this, options);
      $.data(this, 'plugin_' + pluginName, plugin);
    }
    return plugin;
  });
  // Return instance itself, instead of an array
  return plugins.length == 1 ? plugins[0] : plugins;
};
```
Usage
```js
var plug = $(".aa").defaultPluginName();
plug[0].yourOtherFunction("test1"); 
plug[1].yourOtherFunction("test2"); 

```
